[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "v6.15.7"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"